FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=root_semi_g9
ENV MYSQL_USER=user_p2
ENV MYSQL_PASSWORD=proyecto2_semi
ENV MYSQL_DATABASE=Proyecto2
ENV TZ=America/Guatemala

# Copia el archivo SQL a la carpeta /docker-entrypoint-initdb.d/
COPY ./script.sql /docker-entrypoint-initdb.d/

# Expone el puerto MySQL
EXPOSE 3306